---
title: ""
author: ""           
output:
  html_document:
    css: css/style.css
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F, cache = F
)
```

```{r libraries, warnings = F}
library(tidyverse)
library(leaflet)
library(leafpop)
library(leaflet.extras)
library(crosstalk)
library(sf)
library(htmlwidgets)
library(leaflegend)
library(tigris)

```

```{r, results='hide'}
# import data

# import school corporation boundaries 
in_dis <-
  st_read("clean_data/20240607_corporation_bounds.geojson")

# import nearby state boundaries for map
b_states <- states(cb = T, year = 2023) |> 
  filter(NAME == "Illinois" | NAME == "Kentucky" | NAME == "Ohio" | NAME == "Michigan" | NAME == "Missouri" | NAME == "Iowa" | NAME == "West Virginia")

# Indiana state boundary
in_bd <- states(cb = T, year = 2023) |> 
  filter(NAME == "Indiana") 


# assign colors for type
pub <-  '#d95f02'     # public schools
chr <-  '#1b9e77'     # charter schools
pr <-   '#7570b3'     # private (Choice Scholarship) schools


sxfer <- read_csv("clean_data/20240613_transfer_pts_18_24.csv") |> 
  
  
  
  rename('Public' = 'par_ch', 'Charter' = 'p_xfer_chrtr', 'Choice Scholarship' = 'pr_ch_sclrs', "Other" = 'p_xfer_oth') |> 
  # remove unneeded columns
  select(-c(tot_xfr)) |> 
  
  mutate(
    # replace NA's with 0's
    across(
      c(Public, Other, Charter, 'Choice Scholarship'),
      ~replace_na(.,0))
  ) |>
  
  # pivot to long data
  pivot_longer(cols = c(Public, Other, Charter, 'Choice Scholarship'), names_to = 'typ', values_to = 'tot_xfr') |>
  
  group_by(yr, nrl_schl_id, stlmt_corp_id, typ) |>
  mutate(
    # calculate total by yr, nrl and stlmt id
    tot_xfr = sum(tot_xfr),
    
    # assign fill color based on type 
    fillcolor = case_when(
      typ == 'Public' ~              pub, 
      typ == 'Charter' ~             chr, 
      typ == 'Choice Scholarship'  ~ pr
    ),
    
    # assign unique name to identify combiation of stlmt_corp and nrl_schl
    fname = paste0(stlmt_corp_id, "-", nrl_schl_id),
    
    # convert 'other' transfers to 'public'; though Indiana classifies Charter schools as public also, in this case we're making a distinction between parent choice and other public and charter public.
    typ = case_match(typ,
                     "Other" ~ 'Public',
                     .default = typ),
    # add columns for stroke and stroke color for circle marker denoting school corp
    # stroke size
    weight = 0,
    # stroke color 
    color = NA) |>
  
  group_by(stlmt_corp_id, nrl_schl_id, yr, typ) |> 
  
  # with 'Other' and 'public' both now labeled 'public', combine their transfer totals
  mutate(tot_xfr = sum(tot_xfr)) |> 
  
  # remove rows with na fill (rows with formerly 'other' transfer types) to avoid duplicating counts
  filter(!is.na(fillcolor)) |> 
  
  group_by(stlmt_corp_id, yr) |> 
  
  mutate(
    # calculate percent of total transfers to school corporation given row represents
    pct_of_xfr = round(100*(tot_xfr/sum(tot_xfr)),2),
    # convert to log for better circleMarkers in leaflet
    log = log(pct_of_xfr)) |> 
  
  ungroup() |> 
  
  filter(
    # remove rows with zero transfer totals
    stlmt_corp_id != nrl_schl_id &
      tot_xfr > 0) |> 
  
  # add weight for stroke to increase diameter to make smallest markers more visible
  mutate(weight = 2.5)

# add white circle markers for school settlement corporations

sxfer <- rbind(sxfer,
            # create row where the settlement corporation and the enrolled school corporation are the same so it appears as a transfer to itself but rather than having a type color equal to public, charter or choice scholarship, the color is white to more easily locate the school corporation
               sxfer |>
                 ungroup() |>
                 distinct(stlmt_corp_name, .keep_all = T) |>
                 mutate(nrl_schl_id = stlmt_corp_id,
                        nrl_schl_name = stlmt_corp_name,
                        nrl_lat = stlmt_lat,
                        nrl_lon = stlmt_lon,
                        tot_xfr = 0, # set to 0 to not alter total xfer count
                        fname = paste0(stlmt_corp_id, "-", stlmt_corp_id),
                        fillcolor = '#ffffff',
                        # stroke weight
                        weight = 1,
                        # stroke color
                        color = "#000000",
                        typ = 'Public',
                        pct_of_xfr = 0,
                        # add square root figure that reflects square root for average transfer size
                        log = 1.759581))

# new threshold for circle marker radius to ensure enrolled schools with very vew transfers are viewable on map - previously too small. 
sxfer <- sxfer |> 
  filter(yr == 2024) |> 
  group_by(stlmt_corp_name) |> 
  mutate(cut = cut(pct_of_xfr, 9, labels = F),
         cut = if_else(stlmt_corp_name == nrl_schl_name, 5, cut),
         # set color (for circle marker stroke) to match fill for schools and black for originating school corporation
         color = if_else(stlmt_corp_name == nrl_schl_name, "#000000", fillcolor))
  
# make shared data object from sxfer dataframe
schl_data <- SharedData$new(data = sxfer)


```



```{r}
# url components for popups
base_url <- "https://tedschurter-data.s3.us-east-2.amazonaws.com/2024-in-ed-"
end_url <- ".png"

# add custom legend for outgoing transfer types; # basic structure from: stackoverflow.com/questions/58505589/circles-in-legend-for-leaflet-map-with-addcirclemarkers-in-r-without-shiny

# note: if argument is not listed within function(), can't call it later within leaflet

addLegendCustom <- function(map, colors, labels, sizes, title, position, group, opacity = 1, className ){
  
  colorAdditions <- paste0(colors, "; border-radius: 50%; width:", sizes, "px; height:", sizes, "px")
  
  labelAdditions <- paste0("<div style='display: inline-block;height: ", 
                           sizes, "px;margin-top: 4px;line-height: ", sizes, "px;'>", 
                           labels, "</div>")
  
  return(addLegend(map, 
                   colors = colorAdditions, 
                   labels = labelAdditions, 
                   opacity = opacity,
                   title = title, 
                   position = position, 
                   group = group
                   ))
}

map <-  
  leaflet(
    options = leafletOptions(
      minZoom = 6.8,
      maxZoom = 11),
    height = 500
  )|>
    
    setView(lng = -86.95, #-86.75, #-87.05, 
            lat = 39.8, 6) |>
    
    addProviderTiles(providers$CartoDB.Positron, ) |>
    
    
    # polygon layer to show corporation/district boundaries for outgoing layer
    addPolygons(data = in_dis,
                color = "black",
                  #"#111111",
                fillOpacity = .65,
                fillColor = '#fafafa', #"#ffffff",
                weight = .2,
                group = "Outgoing transfers"
    ) |>
  
    # add adjacent and nearby states in order to reduce transparency of labels, etc
  addPolygons(data = b_states,
              color = "black",
              fillOpacity = .8,
              fillColor = '#fafafa', 
              weight = .2,
              group = "Incoming transfers"
  ) |> 
  
  # add polygon for Indiana border
  addPolygons(data = in_bd,
                color = "black",
                fillOpacity = 0,
                fillColor = '#fafafa', 
                weight = .3,
                group = "Incoming transfers"
  )  |> 

    # add circle markers for outgoing transfers from school corporations
    addCircleMarkers (
      data = schl_data,
      ~ nrl_lon,
      ~ nrl_lat,
      radius =  ~cut*1.5,
      fillColor = ~ fillcolor,
      color = ~ color,
      weight = ~weight,
      stroke = T,
      fillOpacity = .85,
      label = ~ nrl_schl_name,
      popup = popupImage(paste0(base_url, sxfer$fname, end_url),
                         width = 350, height = 467), # popup will not autopan on first click if height not explicitly set
      popupOptions =
        popupOptions(keepInView = TRUE,
                     autoPan = TRUE),
      # add grouping
      group = "Outgoing transfers"

    ) |>
  
    # reset button
    addResetMapButton() |>
 
    # custom legend outgoing transfers
    addLegendCustom(
      colors = 
        c(
          "#fc8d62",
          "#66c2a5",
          "#8da0cb"
        ),
      labels = 
        c('Public',
          'Charter',
          'Choice Scholarship'
        ),
      sizes = c(15, 15, 15), 
      position = "topleft", 
      title = 
        paste0("<span style='font-weight:600'>Outgoing transfers</span><br><span style='font-weight:100;font-size: 8pt; line-height: normal'>Select circles for transfer<br>details and test scores</span><br>\u25EF <span style='font-size: 10pt; font-weight:100'>School corporation</span><br><br><span style='font-weight:400; '>Enrolled school types:</span><br><span style='font-weight:100;font-size: 8pt; line-height: normal'>Circle sizes proportional <br>to transfer totals</span>"),
      group = "Outgoing transfers" 
    ) |>
    
    # javascript function to return map to default bounds if popup moves map beyond view
    onRender("function(el, x) {
                          var map = this;
                          map.eachLayer(function(layer) {
  
                            if(layer instanceof L.CircleMarker){
                              layer.on('click', function(e){
  
                                layer.getPopup().on('remove', function () {
  
                                  map.setView(map._initialCenter, map._initialZoom);
                                });
                              })
                              .addTo(map)
                            }
                          });
                        }
    ")
      
  #
 
```

```{r, filter}
# dropdown filter for school corporation of legal settlement
filter <-   
  filter_select(
    id = "filter_stlmt",
    label = "Select school corporation", 
    sharedData = schl_data,
    multiple = F,
    group = ~stlmt_corp_name, 
  )

```



```{r, out-filters}

filt <- list(filter 
             )
bscols(
  # set widths of respective elements; 12 column max available
  widths = c(2,10),
  filt, map)


```



```{js out-filter-select-nrl-map}

<!-- <!--   helpful js function to enable selecting default value in filter; from https://stackoverflow.com/questions/67058016/how-to-set-default-values-in-filter-select-in-crosstalk-in-r-plotly/68024136#68024136  --> -->


function filter_stlmt_corp() {
    document.getElementById("filter_stlmt").getElementsByClassName("selectized")
[0].selectize.setValue("Adams Central Community Schools",  false);
 }

window.onload=function(){
filter_stlmt_corp()
}
```

